### PR TITLE
Add Dockerfile and config.yml for Hub example.

### PR DESCRIPTION
**Pull request by Carreau**
In particular the Dockerfile install build-essential and what is needed
to use cffi / cffi-magic

cc @mjbright

I'm also following http://zero-to-jupyterhub.readthedocs.io/en/latest/setup-helm.html to deloy hub on google cloud, which takes about 20 minutes.

### CODE REVIEW

**Comment by minrk** [comment]
Is there a reason this is starting from scratch instead of using one of the [docker stacks](https://github.com/jupyter/docker-stacks)?

**Comment by Carreau** [comment]
That's derived from helm-charts that does not use conda. I'll see if I can derive from Docker-stack.

**Comment by minrk** [comment]
Not important if this is easier, just checking. It shouldn't really matter how things get installed in the container.

**Comment by Carreau** [comment]
> Not important if this is easier, just checking. It shouldn't really matter how things get installed in the container.

I have things to work locally, but when I base things on  the Docker stack and deploy on gcloud the container is just pending indefinitely. 

```
FROM jupyter/datascience-notebook

WORKDIR /home/$NB_USER/work
RUN pip install pip --upgrade --user && \
    pip install julia --user && \
    julia -e 'Pkg.update();Pkg.add("PyCall")'

ADD . .
RUN rm -rf __pycache__ && \
    rm -rf fabfile.py && \
    rm -rf pycon*

USER root
RUN chown -R $NB_USER .
USER $NB_USER

EXPOSE 8888

CMD jupyterhub-singleuser \
  --port=8888 \
  --ip=0.0.0.0 \
  --user="$JPY_USER" \  # tried with $NB_USER as well. 
  --cookie-name=$JPY_COOKIE_NAME \
  --base-url=$JPY_BASE_URL \
  --hub-prefix=$JPY_HUB_PREFIX \
  --hub-api-url=$JPY_HUB_API_URL
```

I just can't see wha't I'm doing wrong right now. I'l debug that late with Yuvi.

**Comment by Carreau** [comment]
Yuvi and I figured it out. It's the mounting persistent storage thing. 
It needed
```
singleuser:
  storage:
    type: none
```

I'm going to think about this because a base image from docker-stack take ages to pull (which is not great for a tutorial), though it can get R/Python/Julia running at the same time which is cute. 

So I may prepare two images from the tutorial.

**Comment by minrk** [comment]
base-notebook is 200MB, which shouldn't take long to pull, especially into a cloud service.

**Comment by Carreau** [comment]
> base-notebook is 200MB, which shouldn't take long to pull, especially into a cloud service.

Thats because I inherit data-science notebook (to have basic things), but then it pull texlive....
I'll see if I can make a smaller image based on minimal that does not have this extra stuff and may have only a Python 3 kernel.

**Comment by minrk** [comment]
I believe if you set `WORKDIR $HOME` then persistence works with docker-stacks. The failure I see is that it's failing to set CWD to a nonexistent $HOME/work because volume persistence of $HOME deletes that subdirectory.

**Pull request closed without merging**
